---
version: '3.1'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: zero2prod_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRESS_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRESS_PASSWORD:-password}
      - POSTGRES_DB= ${POSTGRESS_DB:-newsletter}
  adminer:
    image: adminer:${ADMINER_VERSION:-latest}
    container_name: zero2prod_adminer
    restart: unless-stopped
    ports:
      - 8080:8080
